apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt-playground
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nuxt-playground
    spec:
      containers:
        - name: nuxt-playground
          image: nathan1658.azurecr.io/nuxt-playground:v3
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nuxt-playground
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: nuxt-playground
